[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rlgym-debugger"
dynamic = ["version"]
description = "A package to create components for the debugger"
readme = "README.md"
authors = [
    { name = "Mathieu Suchet", email = "msuchet63@gmail.com" }
]
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = ["rlgym"]
# Optional: define classifiers for PyPI
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[tool.setuptools.dynamic]
version = {file = "rlgym_debugger/api/VERSION.txt"}

[tool.setuptools.packages.find]
where = ["rlgym_debugger/api/src"]
include = ["rlgym_debugger.api.base*"]

[project.optional-dependencies]
api = [
    "rlgym-debugger-human-player @ file:./rlgym_debugger_human_player/api",
    "rlgym-debugger-multi-agents @ file:./rlgym_debugger_multi_agents/api",
]

rocket-league = [
    "rlgym-debugger-human-player-rocket-league @ file:./rlgym_debugger_human_player/rocket_league"
]

human_player = [
    "rlgym-debugger-human-player @ file:./installs/api/human_player",
    "rlgym-debugger-human-player-rocket-league @ file:./rlgym_debugger_human_player/rocket_league"
]

all = [
    "rlgym-debugger-human-player @ file:./rlgym_debugger_human_player/api",
    "rlgym-debugger-human-player-rocket-league @ file:./installs/rocket_league/human_player",
    "rlgym-debugger-multi-agents @ file:./rlgym_debugger_multi_agents/api"
]