[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rlgym-debugger-human-player-rocket-league"
dynamic = ["version"]
description = "A package that implements a keyboard and controller interface to play in a rocket league environment"
readme = "README.md"
authors = [
    { name = "Mathieu Suchet", email = "msuchet63@gmail.com" }
]
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = ["rlgym-debugger-human-player", "mouse", "keyboard", "pygame"]
# Optional: define classifiers for PyPI
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["rlgym_debugger.rocket_league.human_player*"]

[tool.setuptools.dynamic]
version = {file = "VERSION.txt"}